### ISSUE TITLE
Add learning resources to README file

### ISSUE THREAD

**Issue by saurabhnative** [saurabhnative/foodDeliveryAppFrontend#1]
Add learning resources in README.md section related to axios integration in react, bootstrap usage in react.js and react router tutorials.
Any links to youtube tutorials, official docs or articles from Medium, Dev.to or Hashnode are preferred.

**Comment by iatharva** [comment]
Can you assign this issue to me? so I can resolve it.

**Comment by J-e-e-t** [comment]
I have worked with axios, bootstarp and reactjs. I can recommend good article, docs, youtube links. you can assign me this issue. thanks..

**Comment by saurabhnative** [comment]
@iatharva You can add resources to the repo.

**Comment by iatharva** [comment]
Looks like the resources are already added by @Rishi22-Coding 2 days before. Can I still add more? (Also just wanted to let you know that issue is not assigned to anyone)

**Comment by saurabhnative** [comment]
@iatharva Yes, you can add more resources. I generally directly accept PRs instead of assigning the issues.
